spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

    properties:
      hibernate:
        search:
          default:
            indexmanager: elasticsearch
            elasticsearch:
              required_index_status: yellow
              host: http://localhost:9200
              index_schema_management_strategy: drop-and-create
